import { randomUUID } from "node:crypto";
import { sql } from "drizzle-orm";
import {
	boolean,
	index,
	integer,
	pgTable,
	text,
	timestamp,
	uniqueIndex,
} from "drizzle-orm/pg-core";

export const job = pgTable(
	"Job",
	{
		id: text()
			.primaryKey()
			.notNull()
			.$defaultFn(() => randomUUID()),
		url: text(),
		title: text().notNull(),
		description: text().notNull(),
		createdAt: timestamp({ precision: 3, mode: "string" })
			.default(sql`CURRENT_TIMESTAMP`)
			.notNull(),
		updatedAt: timestamp({ precision: 3, mode: "string" })
			.notNull()
			.$defaultFn(() => new Date().toISOString()),
		source: text().notNull(),
		company: text(),
		location: text(),
		role: text(),
		seniority: text(),
		salary: text(),
		postedAt: timestamp({ precision: 3, mode: "string" }),
		// "published" (default — everything scraped) or "pending" (direct
		// posts awaiting review in /admin).
		status: text().notNull().default("published"),
		postedById: text().references(() => user.id, { onDelete: "set null" }),
		// Structured salary from direct posts, RM per month (min = max for an
		// exact salary). The formatted text also lands in `salary` for display.
		salaryMin: integer(),
		salaryMax: integer(),
		// Direct-post-only fields — deliberately NOT filter dimensions (see
		// job-attributes.ts for the option lists). Scraped rows stay null.
		city: text(),
		arrangement: text(), // remote | hybrid | on-site
		employmentType: text(), // full-time | part-time | internship | contract
		// Email-only applications: url is null and candidates apply by email.
		applyEmail: text(),
		// On-site page slug, direct posts only ("title-company-x7k2p9"). Null
		// for scraped jobs — they have no /jobs/:slug page.
		slug: text(),
	},
	(table) => [
		uniqueIndex("Job_url_key").using(
			"btree",
			table.url.asc().nullsLast().op("text_ops"),
		),
		uniqueIndex("Job_slug_key").using(
			"btree",
			table.slug.asc().nullsLast().op("text_ops"),
		),
	],
);

// --- better-auth core tables ----------------------------------------------
// Generated by @better-auth/cli (better-auth v1.6) and kept verbatim except
// formatting. Lowercase quoted names are intentional — they are better-auth's
// defaults, and renaming models adds config surface for zero gain. PascalCase
// remains the convention for app-owned tables.

export const user = pgTable("user", {
	id: text("id").primaryKey(),
	name: text("name").notNull(),
	email: text("email").notNull().unique(),
	emailVerified: boolean("email_verified").default(false).notNull(),
	image: text("image"),
	createdAt: timestamp("created_at").defaultNow().notNull(),
	updatedAt: timestamp("updated_at")
		.defaultNow()
		.$onUpdate(() => new Date())
		.notNull(),
});

export const session = pgTable(
	"session",
	{
		id: text("id").primaryKey(),
		expiresAt: timestamp("expires_at").notNull(),
		token: text("token").notNull().unique(),
		createdAt: timestamp("created_at").defaultNow().notNull(),
		updatedAt: timestamp("updated_at")
			.$onUpdate(() => new Date())
			.notNull(),
		ipAddress: text("ip_address"),
		userAgent: text("user_agent"),
		userId: text("user_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
	},
	(table) => [index("session_userId_idx").on(table.userId)],
);

export const account = pgTable(
	"account",
	{
		id: text("id").primaryKey(),
		accountId: text("account_id").notNull(),
		providerId: text("provider_id").notNull(),
		userId: text("user_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		accessToken: text("access_token"),
		refreshToken: text("refresh_token"),
		idToken: text("id_token"),
		accessTokenExpiresAt: timestamp("access_token_expires_at"),
		refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
		scope: text("scope"),
		password: text("password"),
		createdAt: timestamp("created_at").defaultNow().notNull(),
		updatedAt: timestamp("updated_at")
			.$onUpdate(() => new Date())
			.notNull(),
	},
	(table) => [index("account_userId_idx").on(table.userId)],
);

export const verification = pgTable(
	"verification",
	{
		id: text("id").primaryKey(),
		identifier: text("identifier").notNull(),
		value: text("value").notNull(),
		expiresAt: timestamp("expires_at").notNull(),
		createdAt: timestamp("created_at").defaultNow().notNull(),
		updatedAt: timestamp("updated_at")
			.defaultNow()
			.$onUpdate(() => new Date())
			.notNull(),
	},
	(table) => [index("verification_identifier_idx").on(table.identifier)],
);
